# Pytorch Tutorial
[link](https://tutorials.pytorch.kr/beginner/pytorch_with_examples.html)

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#1.-What-is-Pytorch?" data-toc-modified-id="1.-What-is-Pytorch?-1">1. What is Pytorch?</a></span></li></ul></div>

## 1. What is Pytorch?
- 가장 큰Replace Numpy + GPU

In [2]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 1.5846e+29, 0.0000e+00],
        [1.5846e+29, 7.0065e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.5846e+29, 5.7522e-31]])


In [10]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6871, 0.9953, 0.9045],
        [0.5031, 0.8302, 0.0385],
        [0.6007, 0.3877, 0.6534],
        [0.1342, 0.4891, 0.1714],
        [0.1956, 0.6684, 0.9717]])


In [11]:
torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0.6871, 0.9953, 0.9045],
        [0.5031, 0.8302, 0.0385],
        [0.6007, 0.3877, 0.6534],
        [0.1342, 0.4891, 0.1714],
        [0.1956, 0.6684, 0.9717]])


In [16]:
x = torch.tensor([5.6,5, 3], dtype=torch.int)
print(x)

tensor([5, 5, 3], dtype=torch.int32)


In [19]:
x = x.new_ones(5, 3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [20]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[-0.9903,  0.0925,  0.1022],
        [ 0.8297,  0.0638, -0.9856],
        [ 0.7057, -0.2434, -0.2847],
        [-0.5425,  1.2251, -1.3452],
        [ 0.4644,  0.1921, -0.3918]])

In [21]:
print(x.size())

torch.Size([5, 3])


In [25]:
x.size()[0]

5

In [27]:
y = torch.rand(5, 3)
print(x, y)

tensor([[-0.9903,  0.0925,  0.1022],
        [ 0.8297,  0.0638, -0.9856],
        [ 0.7057, -0.2434, -0.2847],
        [-0.5425,  1.2251, -1.3452],
        [ 0.4644,  0.1921, -0.3918]]) tensor([[0.8302, 0.2200, 0.7741],
        [0.4561, 0.9848, 0.0715],
        [0.9014, 0.6751, 0.3494],
        [0.1352, 0.4254, 0.7131],
        [0.1080, 0.1188, 0.4367]])


In [28]:
x+y

tensor([[-0.1601,  0.3125,  0.8763],
        [ 1.2858,  1.0486, -0.9140],
        [ 1.6071,  0.4317,  0.0648],
        [-0.4074,  1.6505, -0.6321],
        [ 0.5725,  0.3109,  0.0450]])

In [29]:
torch.add(x, y)

tensor([[-0.1601,  0.3125,  0.8763],
        [ 1.2858,  1.0486, -0.9140],
        [ 1.6071,  0.4317,  0.0648],
        [-0.4074,  1.6505, -0.6321],
        [ 0.5725,  0.3109,  0.0450]])

In [31]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)

tensor([[-0.1601,  0.3125,  0.8763],
        [ 1.2858,  1.0486, -0.9140],
        [ 1.6071,  0.4317,  0.0648],
        [-0.4074,  1.6505, -0.6321],
        [ 0.5725,  0.3109,  0.0450]])

In [32]:
result

tensor([[-0.1601,  0.3125,  0.8763],
        [ 1.2858,  1.0486, -0.9140],
        [ 1.6071,  0.4317,  0.0648],
        [-0.4074,  1.6505, -0.6321],
        [ 0.5725,  0.3109,  0.0450]])

In [33]:
y.add_(x)

tensor([[-0.1601,  0.3125,  0.8763],
        [ 1.2858,  1.0486, -0.9140],
        [ 1.6071,  0.4317,  0.0648],
        [-0.4074,  1.6505, -0.6321],
        [ 0.5725,  0.3109,  0.0450]])

In [53]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [57]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.3968])
-0.39677906036376953


In [59]:
a = torch.ones(4)

print(a)

tensor([1., 1., 1., 1.])


In [60]:
b = a.numpy()

In [61]:
print(b)

[1. 1. 1. 1.]


In [63]:
a.add_(1)

tensor([2., 2., 2., 2.])

In [64]:
print(a)
print(b)

tensor([2., 2., 2., 2.])
[2. 2. 2. 2.]


In [65]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a, b)

[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [66]:
torch.cuda.is_available()

False

In [67]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [68]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [69]:
print(y.grad_fn)

In [71]:
z = y*y*3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [72]:
a = torch.randn(2, 2)
a = ((a*3) / (a-1))
print(a.requires_grad)

False


In [73]:
a.requires_grad_(True)
print(a.requires_grad)

True


In [74]:
b = (a*a).sum()
print(b.grad_fn)

In [76]:
out.backward()

In [77]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [78]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [79]:
x = torch.randn(3, requires_grad=True)
y = x*2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([1853.0392, -212.2708, -679.8311], grad_fn=<MulBackward0>)


In [80]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [81]:
print(x.requires_grad)

True


In [82]:
print((x**2).requires_grad)

True


In [83]:
with torch.no_grad():
    print((x**2).requires_grad)

False


In [84]:
print((x**3).requires_grad)

True


In [85]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


todo:https://tutorials.pytorch.kr/beginner/blitz/neural_networks_tutorial.html